version: '3.7'

services:

  mongo:
    image: mongo
    restart: always
    volumes: 
      - ~/mongo/data:/data/db
    environment:
      MONGO_INITDB_DATABASE: prices
      MONGO_INITDB_ROOT_USERNAME: rocket
      MONGO_INITDB_ROOT_PASSWORD: league

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rocket
      ME_CONFIG_MONGODB_ADMINPASSWORD: league
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/